### ISSUE TITLE
API Key?

### ISSUE THREAD

**Issue by JoaoGabrielCostaa** [nikolaposa/rate-limit#27]
What is API Key?

**Comment by nikolaposa** [comment]
Where did you find "API key", can you point me to the code? If you are referring to README examples, it's just for the sake of demonstrating what can be used as an `$identifier` that is passed to: https://github.com/nikolaposa/rate-limit/blob/master/src/RateLimiter.php#L14. So things such as API key, IP address, User ID, and similar.
