### ISSUE TITLE
Publish new release please

### ISSUE THREAD

**Issue by omnilight** [nikolaposa/rate-limit#29]
There are plenty of useful features merged into master last days.

But there is no new release published, which requires us to require commit directly or dev-master, which is a bad practice.

Could you please publish a new release with this features?

**Comment by nikolaposa** [comment]
What is exactly "plenty" besides APCu implementation: https://github.com/nikolaposa/rate-limit/compare/2.0.0...master ? 

Anyway I'm waiting for authors to finalize their work on few more PRs: https://github.com/nikolaposa/rate-limit/pulls.

**Comment by omnilight** [comment]
I'm waiting for predis adapter https://github.com/nikolaposa/rate-limit/commit/a938795b40d84dd781be99888243b7d106e90b8c

**Comment by nikolaposa** [comment]
I'm using branch alias: https://github.com/nikolaposa/rate-limit/blob/master/composer.json#L56 so you should be able to pull `2.1.*` regularly which will install `dev-master`: https://getcomposer.org/doc/articles/aliases.md#branch-alias.

**Comment by omnilight** [comment]
Ok, thank you

**Comment by nikolaposa** [comment]
Let me know if it works. Otherwise, I expect to publish new version by the end of June...

**Comment by omnilight** [comment]
Definitely it works, just like `composer require nikolaposa/rate-limit:^2.1.0-dev`
