### ISSUE TITLE
Redis Not connecting

### ISSUE THREAD

**Issue by mitmelon** [nikolaposa/rate-limit#30]
This is because Redis was initialised without being connected...

Solution

 ```
//Updated at class RedisRateLimiter
public function __construct(Redis $redis, string $keyPrefix = '')
    {
        $redis->connect('127.0.0.1',6379);
        $this->redis = $redis;
        $this->keyPrefix = $keyPrefix;
    }
```

**Comment by nikolaposa** [comment]
Solution is to inject properly configured (connected) `Redis` instance into `RedisRateLimiter`. Depending on the setup that will be different host/port. Redis configuration is out of rate limiter scope.
