### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by cubecleveland** [nikolaposa/rate-limit#33]
Hi, How do i set up the redis credentials to log into redis servere ?
Also, does the redis connection perssist over calls... what if i already opend a redis connection in the code somewhare can i just pass the connection handle ?

**Comment by nikolaposa** [comment]
> How do i set up the redis credentials to log into redis servere

That is completely up to your application and how you configure services.

>  what if i already opend a redis connection in the code somewhare can i just pass the connection handle

Yes, you can pass the existing, connected Redis instance to `RedisRateLimiter`.
