### ISSUE TITLE
Improve LimitExceeded exception message

### ISSUE THREAD

**Issue by ManInTheBox** [nikolaposa/rate-limit#38]
Currently, it has a typo: https://github.com/nikolaposa/rate-limit/blob/68ea4e5e011769bdfa22c68e75b415b012f41ad2/src/Exception/LimitExceeded.php#L20

`"Limit of has been exceeded by identifier: $identifier"` - should include "rate" as well.

**Comment by nikolaposa** [comment]
Nice catch, thanks for reporting 👍
