### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by JoyceBabu** [nikolaposa/rate-limit#44]
Are there any known incompatibility with PHP 8?

Is it possible to add PHP 8 to composer.json?

**Comment by nikolaposa** [comment]
It's a work in progress: https://github.com/nikolaposa/rate-limit/pull/43. Thank you for reminding me by the way, that PR got stuck.

**Comment by nikolaposa** [comment]
Merged the PR, I'll create a new release tomorrow.
