### ISSUE TITLE
found error when executing new redis

### ISSUE THREAD

**Issue by aratnamirasugab** [nikolaposa/rate-limit#46]
Hi, I tried to implement the library but found error when executing this code

```
use Ratelimit\Rate;
use RateLimit\RedisRateLimiter;
use Redis;

function rateLimiter() {

    $rateLimiter = new RedisRateLimiter(new Redis());

    $status = $rateLimiter->limitSilently(getClientIPAddress(), Rate::perMinute(5));

    dd($status->getRemainingAttempts());
}
```

```
TypeError {▼
  #message: "Argument 2 passed to RateLimit\RedisRateLimiter::__construct() must be of the type integer, none given, called in /usr/share/nginx/html/sellerpanel/app/Helpers/helpers.php on line 1244"
  #code: 0
  #file: "/usr/share/nginx/html/sellerpanel/vendor/nikolaposa/rate-limit/src/RedisRateLimiter.php"
  #line: 27
  -trace: array:57 [▶]
}
```

**Comment by aratnamirasugab** [comment]
Can I use predis as my redis library?

**Comment by nikolaposa** [comment]
That error you are getting is weird. Which version of the library you are using?

**Comment by aratnamirasugab** [comment]
hi @nikolaposa , I am using rate-limit version 1.0

on composer.json it stated like this

```
"nikolaposa/rate-limit": "^1.0"
```

I've followed the readme for the installation, should I manually choose the specific version before installing the library?

**Comment by nikolaposa** [comment]
As you can see: https://github.com/nikolaposa/rate-limit/blob/1.0.1/src/RedisRateLimiter.php#L27, in version 1.x, `RedisRateLimiter::__construct()` accepts 3 parameters. Please switch to using latest, 2.2.0 version, or at least 2.x.

In general, when installing dependencies, never edit `composer.json` manually, always use `composer require` command, for example:

```
composer require nikolaposa/rate-limit
```

That way Composer will resolve version that is appropriate for your system, based on PHP version for example.

**Comment by aratnamirasugab** [comment]
thank you for your kind response! @nikolaposa
