### ISSUE TITLE
Use Rabbit MQ

### ISSUE THREAD

**Issue by mitmelon** [nikolaposa/rate-limit#47]
Is there anyway to use rabbit mq instead of redis?

**Comment by nikolaposa** [comment]
No, RabbitMQ is not supported. You can find the list of all supported drivers [here](https://github.com/nikolaposa/rate-limit/blob/master/README.md#supported-drivers). 

To be honest, I think RabitMQ as a technology is not the right choice for rate limiting patterns at all.
