### ISSUE TITLE
reset wave 1s

### ISSUE THREAD

**Issue by fxm5547** [nikolaposa/rate-limit#5]
- in `RedisRateLimiter.php`，you should use pttl
```php
    protected function ttl(string $key) : int
    {
        return max((int) ceil($this->redis->pttl($key) / 1000), 0);
    }
```

- in `AbstractRateLimiter.php`, you should use `microtime`
```php
    public function getResetAt(string $key) : int
    {
        return time() + $this->ttl($key);
    }
```

**Comment by nikolaposa** [comment]
What's the benefit of using Redis `pttl` over `ttl`?

**Comment by fxm5547** [comment]
when you test, you can find `reset` is not Unfixe, it is wave 1s.

**Comment by fxm5547** [comment]
@nikolaposa when you test, you can find reset is Unfixed, it is wave 1s.

**Comment by nikolaposa** [comment]
Fixed with: https://github.com/nikolaposa/rate-limit/pull/6.
